name: Deploy to GitHub Pages

# Trigger workflow on push to the main branch
on:
  push:
    branches:
      - main # This will run the workflow whenever you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js (Optional, if you're using Node.js for your project)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Choose the version of Node.js (if needed)

      # Install dependencies (skip this if your project doesn't use npm)
      - name: Install dependencies
        run: npm install

      # Build your project (skip this if you're not using a build tool)
      - name: Build
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Path to the directory you want to deploy (e.g., ./build or ./dist)
